### ISSUE TITLE
Documentação do Contexto - Introdução e Problema

### ISSUE THREAD

**Issue by willy-r** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e1-proj-web-t9-saudavelmente#3]

**Comment by simoesvinicius** [comment]
# Introdução

De acordo com a Organização Mundial da Saúde (OMS), o número de pessoas com transtornos mentais como a depressão e o transtorno de ansiedade tem crescido em todo o mundo. Os fatores podem estar relacionados à problemas socioeconômicos, genéticos, neurológicos ou pessoais.

Tendo isso em vista, este projeto criará uma plataforma virtual que conecta os pacientes que necessitam de tratamentos à profissionais da saúde, sendo eles psicólogos, psiquiatras ou terapeutas. Através dessa conexão será possível marcar consultas, compartilhar experiências e acessar recursos educativos, capacitando os indivíduos a estabelecer um equilíbrio saudável entre a vida digital e o bem-estar mental.

O projeto reconhece a tecnologia não só como um catalisador, mas como parte da solução. Com uma interface amigável, almeja guiar os usuários na jornada de adotar estratégias saudáveis para enfrentar os desafios da era digital enquanto preservam sua saúde emocional. Esta iniciativa visa ser um farol de apoio, promovendo uma relação harmoniosa com a tecnologia e o fortalecimento da saúde mental em nosso mundo conectado.

## Problema
A saúde mental se tornou uma preocupação crescente na sociedade moderna devido a fatores como estresse elevado, pressões sociais, mudanças de estilo de vida e acesso constante à tecnologia. Muitas pessoas enfrentam problemas como ansiedade, depressão, transtornos de humor, isolamento social, falta de sono, baixa autoestima e estresse crônico, muitas vezes sem acesso ou recursos para buscar ajuda profissional adequada. A estigmatização em torno das questões de saúde mental também pode dificultar a busca por tratamento.
